version: '3'

services:
  app:
    build: .
    environment:
      TWITTER_API_KEY: ${TWITTER_API_KEY}
      TWITTER_SECRET_KEY: ${TWITTER_SECRET_KEY}
      TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_TOKEN_SECRET: ${TWITTER_ACCESS_TOKEN_SECRET}
    command: 'run --allow-net --allow-env mod.ts'
